"""permission enum updated

Revision ID: 2f045d760796
Revises: 3019b55e0ff5
Create Date: 2024-01-26 16:45:09.477564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f045d760796"
down_revision = "3019b55e0ff5"
branch_labels = None
depends_on = None

TABLE_NAME = "user"
COLUMN_NAME = "permission"
COLUMN_TYPE_NAME = "permissionenum"

old_type = sa.Enum("IS_OPERATOR", "ACTIVE", name=COLUMN_TYPE_NAME)
new_type = sa.Enum("IS_OPERATOR", "IS_ADMIN", "IS_MANAGER", name=COLUMN_TYPE_NAME)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=old_type,
        type_=new_type,
        postgresql_using=f"{COLUMN_NAME}::text::{COLUMN_TYPE_NAME}",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=new_type,
        type_=old_type,
        postgresql_using=f"{COLUMN_NAME}::text::{COLUMN_TYPE_NAME}",
    )
    # ### end Alembic commands ###
